### ISSUE TITLE
`web3` Parameter Naming

### ISSUE THREAD

**Issue by karlfloersch** [skmgoldin/deploy-monster#4]
In the `config.json` here: https://github.com/skmgoldin/deploy-monster/blob/master/conf.json#L9 I think the option `web3` could be confusing. It seems you shorten the "web3 provider" to just `web3`. Maybe it should be called `provider`? 

```
[...]
  },
  "web3": "http://localhost:8545"
}
```

**Comment by skmgoldin** [comment]
I thought I changed this already, but maybe that was just a dream. Yes, it is confusing, I will change it.

**Comment by skmgoldin** [comment]
Resolved in v1.0.0
